using System.Linq;

namespace LeetCode
{
    /* https://leetcode.com/problems/find-the-difference/
     * 389. Find the Difference
        Total Accepted: 3985
        Total Submissions: 7109
        Difficulty: Easy
        Given two strings s and t which consist of only lowercase letters.

        String t is generated by random shuffling string s and then add one more letter at a random position.

        Find the letter that was added in t.

        Example:

        Input:
        s = "abcd"
        t = "abcde"

        Output:
        e

        Explanation:
        'e' is the letter that was added.
     */
    internal class FindTheDifference
    {
        public char Solution(string s, string t)
        {
            if (string.IsNullOrEmpty(s) && string.IsNullOrEmpty(t))
            {
                return new char();
            }
            char[] sArray = s.OrderBy(x => x).ToArray();
            char[] tArray = t.OrderBy(y => y).ToArray();
            
            int i = 0, j = 0;
            while (i < sArray.Length)
            {
                if (sArray[i] == tArray[j])
                {
                    i++; j++;
                }
                else if (sArray[i] > tArray[j])
                {
                    return tArray[j];
                }
            }
            return tArray[j];
        }
    }
}
